### ISSUE TITLE
not sprinting when using false son's special skill

### ISSUE THREAD

**Issue by zeptojoule** [goldenguy00/AutoSprint#3]
normally you are able to sprint when charging up false son's special skill (the laser) but this mod makes this impossible

**Comment by goldenguy00** [comment]
dragonyck's version will likely be the version to use going foward, but ill try to get around to fixing that later today. https://thunderstore.io/package/Dragonyck/RTAutoSprintEx/

**Comment by goldenguy00** [comment]
fixed in 1.0.8
