### ISSUE TITLE
Not working with RoR2BepInExPack's "Frame Rate Dependant Logic" fix

### ISSUE THREAD

**Issue by DumbCodeGenerator** [goldenguy00/AutoSprint#6]
When enabling "Fix Frame Rate Dependant Logic" in [RoR2BepInExPack](https://github.com/risk-of-thunder/RoR2BepInExPack) config, auto sprint stops working

_I'm not sure where I should create an issue: here or on the RoR2BepInExPack page_

**Comment by goldenguy00** [comment]
I have notified the authors of this issue. it breaks all autosprint versions, not just mine and there's nothing i can do to fix it other than rewriting how the hooks work (planned but wayyy in the future). Hopefully next bepinex update uses less destructive strategies...
